### PR TITLE
Enabled uncaughtException logging

### PR DESCRIPTION
**Pull request by SwinX**
Always prints uncaught exceptions

### CODE REVIEW

**Comment by SevInf** [comment]
Won't qDebug enabled by default will make everything slower?
And where exactly uncaught exceptions can happen?
All commands are wrapped in `Q.fcall` and this means majority of execptions will cause promise rejection and will be handled [here](https://github.com/gemini-testing/gemini/blob/master/lib/cli/errors.js#L7). The only reason where exception can be uncaught that comes to my mind is error handler itself or CLI setup code.

**Comment by j0tunn** [comment]
@SevInf Any event handler in any plugin can throw uncaught exception
But yes, I don't think that qDebug enabled by default is a good idea

**Comment by SwinX** [comment]
>And where exactly uncaught exceptions can happen?

For instance right now there is an error in HTML reporter related to failure in opening diff file. This error is not being print anywhere. This handler will show it. 

>But yes, I don't think that qDebug enabled by default is a good idea

:ok:, will move it under `debug` flag.

**Comment by SwinX** [comment]
:up:

**Comment by SevInf** [comment]
Got it.
I don't think it should be done in `gemini.js`. This is public API entrypoint for usage as library and libraries should not install global event handlers.
The correct place for it will be `cli.js` and it might be good idea to use `cli/errors/handleError` for consistency.

**Pull request merged**
