### PR TITLE
Added name to NoRefImageError

### PR DESCRIPTION
**Pull request by SwinX**

### CODE REVIEW

**Comment by SevInf** [comment]
Actually, the only reason to have `NoRefImageError` was now dead `referenceImageAbsence` option. I think the error now can be just replaced with `StateError`

**Comment by SwinX** [comment]
@SevInf  No, this specific error needed in `gemini-gui` in order to implement reference saving feature. So removing is not an option.

**Comment by SevInf** [comment]
:ok:

**Comment by sipayRT** [comment]
ok

**Pull request merged**
