### PR TITLE
Update commands.md

### PR DESCRIPTION
**Pull request by vladislav-sevostyanov**
Misspelling

### CODE REVIEW

**Comment by sipayRT** [comment]
hi!
can you rename your commit message to `chore: misspelling`? And I'll merge it

**Comment by vladislav-sevostyanov** [comment]
done

**Comment by vladislav-sevostyanov** [comment]
Hello! Sorry, how i can do that?

**Comment by DudaGod** [comment]
@vladislav-sevostyanov 
`git commit --amend` - > `chore: misspelling`

**Comment by vladislav-sevostyanov** [comment]
Thanks. I did it. Achievement of the day

**Comment by DudaGod** [comment]
Hm, you did it wrong =(
Look at the number of your commits. It should be one. Try again =)
```
git reset 524d932 --hard
git push origin +patch-1
```

**Comment by vladislav-sevostyanov** [comment]
$ git branch
  master
* patch-1
$ git reset 524d932 --hard
HEAD сейчас на 524d932 Update commands.md
$ git push origin +patch-1
Everything up-to-date

I did like this: https://help.github.com/articles/changing-a-commit-message/#amending-older-or-multiple-commit-messages

**Comment by DudaGod** [comment]
Good job.

**Pull request merged**
