### PR TITLE
chore: bump wd to ^1.0.0

### PR DESCRIPTION
**Pull request by nordstrand**
wd 0.4 has some badly outdated transitive dependencies.

### CODE REVIEW

**Comment by SevInf** [comment]
Looks like wd 1.0.0 [no longer support node 4](https://github.com/admc/wd/blob/master/doc/release-notes.md#100) and we still need it.

**Comment by j0tunn** [comment]
Closing for now. Will be updated after migration to node@6.x+

**Comment by lo1tuma** [comment]
Is there an update regarding this? I’m using gemini 5 alpha-3 with nodejs 8 and get a lot of deprecation warnings from wd@0.4.0 [which have been fixed](https://github.com/admc/wd/pull/456) in the latest version of wd.

**Comment by eGavr** [comment]
@lo1tuma 

Unfortunately there is no any update.

But we will update wd as soon as possible.

Nowadays, it is vital for our team to support node@v4.

Yes, we possibly can create support branch `support/4.x`, but gemini is being developed Intensively, so each commit should be ported into several branches, such flow is really complicated.

**Pull request closed without merging**
